spring:
  datasource:
    url: jdbc:mysql://localhost:3306/danggn?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: example
    password: example

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create